version: "3.9"
services:
  db:
    image: "postgres:13"
    environment:
      POSTGRES_DB: ss
      POSTGRES_USER: ss
      POSTGRES_PASSWORD: dev
      PGUSER: ss
    healthcheck:
      test: ["CMD", "psql", "-c", "select 1"]
      interval: 1s
      retries: 120
  moto-server:
    image: "motoserver/moto:3.0.1"
  storage-service:
    image: storage-service
    build:
      context: ../
      target: builder
    depends_on:
      db:
        condition: service_healthy
      moto-server:
        condition: service_started
    environment:
      - PGUSER=ss
      - PGPASSWORD=dev
      - PGHOST=db
      - PGDATABASE=ss
      - SS_USER=test
      - SS_PWHASH=9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
      - S3_ENDPOINT=http://moto-server:5000
      - S3_ACCESSKEYID=dev
      - S3_SECRETACCESSKEY=dev
      - S3_FORCE_PATH_STYLE=true
      - SS_MAXOBJECTSPERBUCKET=10
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "const c=new require('net').Socket();c.connect(5900);c.on('connect',()=>process.exit(0))",
        ]
      interval: 1s
      retries: 20
    command: ["npm", "start"]
  test:
    image: storage-service
    depends_on:
      storage-service:
        condition: service_healthy
    environment:
      - PGUSER=ss
      - PGPASSWORD=dev
      - PGHOST=db
      - PGDATABASE=ss
      - SS_USER=test
      - SS_PWHASH=9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
      - S3_ENDPOINT=http://moto-server:5000
      - S3_ACCESSKEYID=dev
      - S3_SECRETACCESSKEY=dev
      - S3_FORCE_PATH_STYLE=true
      - SS_MAXOBJECTSPERBUCKET=10
    command: ["npm", "test"]
  lint:
    image: storage-service
    depends_on:
      storage-service:
        condition: service_healthy
    environment:
      - PGUSER=ss
      - PGPASSWORD=dev
      - PGHOST=db
      - PGDATABASE=ss
      - SS_USER=test
      - SS_PWHASH=9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
      - S3_ENDPOINT=http://moto-server:5000
      - S3_ACCESSKEYID=dev
      - S3_SECRETACCESSKEY=dev
      - S3_FORCE_PATH_STYLE=true
      - SS_MAXOBJECTSPERBUCKET=10
    command: ["npm", "run", "lint"]
